INSERT INTO produtos_produto (nome, categoria, unidade, data_validade, created_at) VALUES
('Arroz', 'Cereal', 'kg', DATE('now', '+30 days'), DATE('now')),
('Feijão', 'Leguminosa', 'kg', DATE('now', '+60 days'), DATE('now')),
('Macarrão', 'Massa', 'pacote', DATE('now', '+90 days'), DATE('now')),
('Farinha de Trigo', 'Farinha', 'kg', DATE('now', '+120 days'), DATE('now')),
('Açúcar', 'Açúcar', 'kg', DATE('now', '+150 days'), DATE('now')),
('Sal', 'Condimento', 'kg', DATE('now', '+180 days'), DATE('now')),
('Óleo de Soja', 'Óleo', 'litro', DATE('now', '+210 days'), DATE('now')),
('Leite Integral', 'Laticínio', 'litro', DATE('now', '+7 days'), DATE('now')),
('Café', 'Bebida', 'pacote', DATE('now', '+240 days'), DATE('now')),
('Manteiga', 'Laticínio', 'kg', DATE('now', '+30 days'), DATE('now')),
('Queijo Mussarela', 'Laticínio', 'kg', DATE('now', '+45 days'), DATE('now')),
('Presunto', 'Embutido', 'kg', DATE('now', '+30 days'), DATE('now')),
('Pão Francês', 'Panificação', 'unidade', DATE('now', '+1 days'), DATE('now')),
('Biscoito Recheado', 'Biscoito', 'pacote', DATE('now', '+365 days'), DATE('now')),
('Chocolate ao Leite', 'Doce', 'barra', DATE('now', '+365 days'), DATE('now')),
('Refrigerante Cola', 'Bebida', 'litro', DATE('now', '+180 days'), DATE('now')),
('Suco de Laranja', 'Bebida', 'litro', DATE('now', '+30 days'), DATE('now')),
('Água Mineral', 'Bebida', 'litro', DATE('now', '+730 days'), DATE('now')),
('Cerveja Pilsen', 'Bebida Alcoólica', 'litro', DATE('now', '+365 days'), DATE('now')),
('Vinho Tinto Seco', 'Bebida Alcoólica', 'garrafa', DATE('now', '+1825 days'), DATE('now')),
('Carne Bovina', 'Carne', 'kg', DATE('now', '+3 days'), DATE('now')),
('Carne Suína', 'Carne', 'kg', DATE('now', '+3 days'), DATE('now')),
('Frango Resfriado', 'Carne', 'kg', DATE('now', '+3 days'), DATE('now')),
('Peixe Congelado', 'Peixe', 'kg', DATE('now', '+30 days'), DATE('now')),
('Linguiça Calabresa', 'Embutido', 'kg', DATE('now', '+15 days'), DATE('now')),
('Salsicha', 'Embutido', 'kg', DATE('now', '+15 days'), DATE('now')),
('Ovos', 'Ovo', 'dúzia', DATE('now', '+15 days'), DATE('now')),
('Margarina', 'Laticínio', 'kg', DATE('now', '+180 days'), DATE('now')),
('Iogurte Natural', 'Laticínio', 'unidade', DATE('now', '+15 days'), DATE('now')),
('Creme de Leite', 'Laticínio', 'lata', DATE('now', '+365 days'), DATE('now')),
('Leite Condensado', 'Laticínio', 'lata', DATE('now', '+365 days'), DATE('now')),
('Molho de Tomate', 'Molho', 'lata', DATE('now', '+365 days'), DATE('now')),
('Ketchup', 'Molho', 'frasco', DATE('now', '+365 days'), DATE('now')),
('Maionese', 'Molho', 'frasco', DATE('now', '+180 days'), DATE('now')),
('Mostarda', 'Molho', 'frasco', DATE('now', '+180 days'), DATE('now')),
('Vinagre de Álcool', 'Condimento', 'litro', DATE('now', '+730 days'), DATE('now')),
('Azeite de Oliva', 'Óleo', 'litro', DATE('now', '+730 days'), DATE('now')),
('Milho Verde', 'Conserva', 'lata', DATE('now', '+365 days'), DATE('now')),
('Ervilha', 'Conserva', 'lata', DATE('now', '+365 days'), DATE('now')),
('Palmito', 'Conserva', 'vidro', DATE('now', '+365 days'), DATE('now')),
('Azeitona Verde', 'Conserva', 'vidro', DATE('now', '+365 days'), DATE('now')),
('Sardinha em Óleo', 'Conserva', 'lata', DATE('now', '+365 days'), DATE('now')),
('Atum em Água', 'Conserva', 'lata', DATE('now', '+365 days'), DATE('now')),
('Gelatina de Morango', 'Sobremesa', 'pacote', DATE('now', '+365 days'), DATE('now')),
('Pudim de Leite', 'Sobremesa', 'unidade', DATE('now', '+3 days'), DATE('now')),
('Sorvete de Chocolate', 'Sobremesa', 'litro', DATE('now', '+30 days'), DATE('now')),
('Pipoca de Micro-ondas', 'Salgadinho', 'pacote', DATE('now', '+365 days'), DATE('now')),
('Batata Palha', 'Salgadinho', 'pacote', DATE('now', '+180 days'), DATE('now')),
('Amendoim Torrado', 'Salgadinho', 'pacote', DATE('now', '+180 days'), DATE('now')),
('Castanha de Caju', 'Salgadinho', 'pacote', DATE('now', '+180 days'), DATE('now')),
('Nozes', 'Salgadinho', 'pacote', DATE('now', '+180 days'), DATE('now')),
('Uva Passa', 'Fruta Seca', 'pacote', DATE('now', '+365 days'), DATE('now')),
('Damasco Seco', 'Fruta Seca', 'pacote', DATE('now', '+365 days'), DATE('now')),
('Ameixa Seca', 'Fruta Seca', 'pacote', DATE('now', '+365 days'), DATE('now')),
('Banana Passa', 'Fruta Seca', 'pacote', DATE('now', '+365 days'), DATE('now')),
('Maçã', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Banana', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Laranja', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Uva', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Pera', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Mamão', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Melancia', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Abacaxi', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Manga', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Morango', 'Fruta', 'kg', DATE('now', '+3 days'), DATE('now')),
('Abacate', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Limão', 'Fruta', 'kg', DATE('now', '+7 days'), DATE('now')),
('Cenoura', 'Legume', 'kg', DATE('now', '+15 days'), DATE('now')),
('Batata', 'Legume', 'kg', DATE('now', '+30 days'), DATE('now')),
('Tomate', 'Legume', 'kg', DATE('now', '+7 days'), DATE('now')),
('Cebola', 'Legume', 'kg', DATE('now', '+30 days'), DATE('now')),
('Alho', 'Legume', 'kg', DATE('now', '+60 days'), DATE('now')),
('Pimentão', 'Legume', 'kg', DATE('now', '+7 days'), DATE('now')),
('Abobrinha', 'Legume', 'kg', DATE('now', '+7 days'), DATE('now')),
('Berinjela', 'Legume', 'kg', DATE('now', '+7 days'), DATE('now')),
('Chuchu', 'Legume', 'kg', DATE('now', '+7 days'), DATE('now')),
('Pepino', 'Legume', 'kg', DATE('now', '+7 days'), DATE('now')),
('Alface', 'Verdura', 'unidade', DATE('now', '+3 days'), DATE('now')),
('Couve', 'Verdura', 'unidade', DATE('now', '+3 days'), DATE('now')),
('Espinafre', 'Verdura', 'unidade', DATE('now', '+3 days'), DATE('now')),
('Brócolis', 'Verdura', 'unidade', DATE('now', '+3 days'), DATE('now')),
('Repolho', 'Verdura', 'unidade', DATE('now', '+7 days'), DATE('now')),
('Salsinha', 'Erva', 'maço', DATE('now', '+3 days'), DATE('now')),
('Cebolinha', 'Erva', 'maço', DATE('now', '+3 days'), DATE('now')),
('Manjericão', 'Erva', 'maço', DATE('now', '+3 days'), DATE('now'));
