###
POST http://127.0.0.1:8000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "laislemossouza@gmail.com",
    "password": "lais*89ste"
}

###
GET http://127.0.0.1:8000/produtos/all/ HTTP/1.1

###
POST http://127.0.0.1:8000/produtos/create/ HTTP/1.1
content-type: application/json

{
    "nome": "feijão",
    "categoria": "grãos",
    "unidade": "kg",
    "data_validade": "2026-04-24"
}