# Generated by Django 5.2 on 2025-04-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_quantidade_produto_creat_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='creat_at',
            new_name='created_at',
        ),
    ]
